/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaabrigoanimais.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistemaabrigoanimais.Adocao;
import com.mycompany.sistemaabrigoanimais.Animal;
import com.mycompany.sistemaabrigoanimais.Consulta;
import com.mycompany.sistemaabrigoanimais.persistencia.IAdocaoDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.AdocaoDAOImplPostgres;
import com.mycompany.sistemaabrigoanimais.persistencia.IAnimalDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.AnimalDAOImplPostgres;
import com.mycompany.sistemaabrigoanimais.persistencia.IConsultaDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.ConsultaDAOImplPostgres;
/**
 *
 * @author Giovana
 */
public class AdocaoJPanel extends javax.swing.JPanel {
    private IAdocaoDAO adocaoDAO = new AdocaoDAOImplPostgres();
    private IAnimalDAO animalDAO = new AnimalDAOImplPostgres();
    private IConsultaDAO consultaDAO = new ConsultaDAOImplPostgres();
    private int idSelecionado = -1;
    /**
     * Creates new form AdocaoJPanel
     */
    public AdocaoJPanel() {
        initComponents();
        carregarSeletores();
        carregarTabela();
    }
    private void carregarTabela() {
        DefaultTableModel dfm = (DefaultTableModel) tabela.getModel();
        dfm.setRowCount(0);
        String termo = buscarJTextField.getText().toLowerCase();

        for (Adocao ad : adocaoDAO.consultar()) {
            String nomeAni = "Desconhecido";
            for(Animal a : animalDAO.consultar()) {
                if(a.getId() == ad.getAnimal().getId()) { nomeAni = a.getNome(); break; }
            }

            if (termo.isEmpty() || ad.getAdotante().toLowerCase().contains(termo) || nomeAni.toLowerCase().contains(termo)) {
                Object[] linha = { ad.getId(), ad.getDataAdocao(), nomeAni, ad.getAdotante() };
                dfm.addRow(linha);
            }
        }
    }
    
    private void limparCampos() {
        dataAdocaoJTextField.setText("");
        adotanteJTextField.setText("");
        buscarJTextField.setText("");
        animalJComboBox.setSelectedIndex(-1); 
        idSelecionado = -1;
    }
    
    private void carregarSeletores() {
        animalJComboBox.removeAllItems();
        for (Animal a : animalDAO.consultar()) {
            if ("Resgatado".equalsIgnoreCase(a.getStatus())) {
                animalJComboBox.addItem(a.getNome());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataAdocaoJLabel = new javax.swing.JLabel();
        dataAdocaoJTextField = new javax.swing.JTextField();
        adotanteJLabel = new javax.swing.JLabel();
        adotanteJTextField = new javax.swing.JTextField();
        animalJLabel = new javax.swing.JLabel();
        animalJComboBox = new javax.swing.JComboBox<>();
        buscarJLabel = new javax.swing.JLabel();
        buscarJTextField = new javax.swing.JTextField();
        tabelaScroll = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        buscarJButton = new javax.swing.JButton();
        cancelarJButton = new javax.swing.JButton();
        salvarJButton = new javax.swing.JButton();
        editarJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        voltarJButton = new javax.swing.JButton();

        dataAdocaoJLabel.setText("Data Adoção:");

        adotanteJLabel.setText("Adotante:");

        adotanteJTextField.addActionListener(this::adotanteJTextFieldActionPerformed);

        animalJLabel.setText("Animal:");

        animalJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buscarJLabel.setText("Buscar:");

        buscarJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarJTextFieldKeyReleased(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Data Adoção", "Animal", "Adotante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaScroll.setViewportView(tabela);

        buscarJButton.setText("Buscar");

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(this::cancelarJButtonActionPerformed);

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        voltarJButton.setText("Voltar");
        voltarJButton.addActionListener(this::voltarJButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataAdocaoJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataAdocaoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adotanteJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adotanteJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(animalJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(animalJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buscarJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscarJTextField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscarJButton))
                                    .addComponent(tabelaScroll))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editarJButton)
                                    .addComponent(excluirJButton)
                                    .addComponent(voltarJButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(salvarJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelarJButton)))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataAdocaoJLabel)
                    .addComponent(dataAdocaoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adotanteJLabel)
                    .addComponent(adotanteJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animalJLabel)
                    .addComponent(animalJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarJButton)
                    .addComponent(salvarJButton))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarJLabel)
                    .addComponent(buscarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarJButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adotanteJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adotanteJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adotanteJTextFieldActionPerformed

    private void buscarJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarJTextFieldKeyReleased
        carregarTabela();
    }//GEN-LAST:event_buscarJTextFieldKeyReleased

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        try {
            Adocao ad = new Adocao();
            ad.setDataAdocao(dataAdocaoJTextField.getText());
            ad.setAdotante(adotanteJTextField.getText());

            String nomeSelecionado = animalJComboBox.getSelectedItem().toString();
            Animal animalEncontrado = null;
            for(Animal a : animalDAO.consultar()){
                if(a.getNome().equals(nomeSelecionado)){
                    animalEncontrado = a;
                    break;
                }
            }
            ad.setAnimal(animalEncontrado);

            if (idSelecionado == -1) {
                adocaoDAO.inserir(ad);

                animalEncontrado.setStatus("Adotado");
                animalDAO.atualizar(animalEncontrado);

                for (Consulta c : consultaDAO.consultar()) {
                    if (c.getAnimal().getId() == animalEncontrado.getId()) {
                        consultaDAO.remover(c);
                    }
                }

                JOptionPane.showMessageDialog(this, "Adoção concluída! Animal e Consultas atualizados.");
            } else {
                ad.setId(idSelecionado);
                adocaoDAO.atualizar(ad);
                JOptionPane.showMessageDialog(this, "Dados da adoção atualizados!");
            }

            carregarTabela();
            carregarSeletores(); 
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma adoção na tabela!");
            return;
        }

        int id = (int) tabela.getValueAt(linha, 0);
        for (Adocao ad : adocaoDAO.consultar()) {
            if (ad.getId() == id) {
                idSelecionado = ad.getId();
                dataAdocaoJTextField.setText(ad.getDataAdocao());
                adotanteJTextField.setText(ad.getAdotante());
                animalJComboBox.setSelectedItem(ad.getAnimal().getNome());
                break;
            }
        }
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha == -1) return;

        int confirma = JOptionPane.showConfirmDialog(this, "Deseja excluir este registro de adoção?");
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                int id = (int) tabela.getValueAt(linha, 0);
                Adocao ad = new Adocao();
                ad.setId(id);
                adocaoDAO.remover(ad);

                JOptionPane.showMessageDialog(this, "Registro excluído!");
                carregarTabela();
                carregarSeletores();
                limparCampos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        limparCampos();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void voltarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarJButtonActionPerformed
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof TelaJFrame) {
            ((TelaJFrame) win).limparPainelPrincipal();
        }
    }//GEN-LAST:event_voltarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adotanteJLabel;
    private javax.swing.JTextField adotanteJTextField;
    private javax.swing.JComboBox<String> animalJComboBox;
    private javax.swing.JLabel animalJLabel;
    private javax.swing.JButton buscarJButton;
    private javax.swing.JLabel buscarJLabel;
    private javax.swing.JTextField buscarJTextField;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JLabel dataAdocaoJLabel;
    private javax.swing.JTextField dataAdocaoJTextField;
    private javax.swing.JButton editarJButton;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelaScroll;
    private javax.swing.JButton voltarJButton;
    // End of variables declaration//GEN-END:variables
}
