/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaabrigoanimais.ui;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistemaabrigoanimais.Animal;
import com.mycompany.sistemaabrigoanimais.persistencia.IAnimalDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.AnimalDAOImplPostgres;
/**
 *
 * @author Giovana
 */
public class AnimalJPanel extends javax.swing.JPanel {
    
    private IAnimalDAO animalDAO = new AnimalDAOImplPostgres();
    /**
     * Creates new form AnimalJPanel
     */
    public AnimalJPanel() {
        initComponents();
        carregarTabela();
    }
    
    private void carregarTabela(){
        
        DefaultTableModel dfm = (DefaultTableModel) tabela.getModel();
        dfm.setRowCount(0); 

        List<Animal> lista = animalDAO.consultar(); 
        for (Animal animal : lista) {
            Object[] linha = new Object[6]; 
            linha[0] = animal.getId();
            linha[1] = animal.getNome();
            linha[2] = animal.getEspecie();
            linha[3] = animal.getRaca();
            linha[4] = animal.getIdade();
            linha[5] = animal.getStatus();
            dfm.addRow(linha); 
        }
    }
    
    private void limparCampos() {
        idJTextField.setText("");
        nomeJTextField.setText("");
        especieJTextField.setText("");
        racaJTextField.setText("");
        idadeJTextField.setText("");
        statusJTextField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        nomeJLabel = new javax.swing.JLabel();
        nomeJTextField = new javax.swing.JTextField();
        especieJLabel = new javax.swing.JLabel();
        especieJTextField = new javax.swing.JTextField();
        salvarJButton = new javax.swing.JButton();
        racaJLabel = new javax.swing.JLabel();
        racaJTextField = new javax.swing.JTextField();
        idadeJLabel = new javax.swing.JLabel();
        idadeJTextField = new javax.swing.JTextField();
        statusJLabel = new javax.swing.JLabel();
        statusJTextField = new javax.swing.JTextField();
        cancelarJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        scrollTabela = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        editarJButton = new javax.swing.JButton();
        idJLabel = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        nomeJLabel.setText("Nome:");

        especieJLabel.setText("Espécie:");

        especieJTextField.addActionListener(this::especieJTextFieldActionPerformed);

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        racaJLabel.setText("Raça:");

        racaJTextField.addActionListener(this::racaJTextFieldActionPerformed);

        idadeJLabel.setText("Idade:");

        statusJLabel.setText("Status:");

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(this::cancelarJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTabela.setViewportView(tabela);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        idJLabel.setText("Id: ");

        idJTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(racaJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(racaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(idadeJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(statusJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(statusJTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nomeJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(especieJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(especieJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(idJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(excluirJButton)
                .addGap(18, 18, 18)
                .addComponent(editarJButton)
                .addGap(18, 18, 18)
                .addComponent(salvarJButton)
                .addGap(18, 18, 18)
                .addComponent(cancelarJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJLabel)
                    .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especieJLabel)
                    .addComponent(especieJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idJLabel)
                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(racaJLabel)
                    .addComponent(racaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idadeJLabel)
                    .addComponent(idadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusJLabel)
                    .addComponent(statusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarJButton)
                    .addComponent(cancelarJButton)
                    .addComponent(excluirJButton)
                    .addComponent(editarJButton))
                .addGap(45, 45, 45)
                .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        Animal animal = new Animal();
        try {
            animal.setNome(nomeJTextField.getText());
            animal.setEspecie(especieJTextField.getText());
            animal.setRaca(racaJTextField.getText());
            animal.setIdade(Integer.parseInt(idadeJTextField.getText())); 
            animal.setStatus(statusJTextField.getText());

            String idStr = idJTextField.getText();
            if (idStr.equals("")) {
                animalDAO.inserir(animal);
            } else {
                animal.setId(Integer.parseInt(idStr));
                animalDAO.atualizar(animal);
            }

            JOptionPane.showMessageDialog(this, "Animal salvo com sucesso!");
            limparCampos();
            carregarTabela(); 
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + erro.getMessage());
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void especieJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieJTextFieldActionPerformed

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        limparCampos();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int id = (int) tabela.getValueAt(linhaSelecionada, 0);

            Animal a = new Animal();
            a.setId(id);

            int confirma = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?");
            if (confirma == JOptionPane.YES_OPTION) {
                animalDAO.remover(a);
                carregarTabela();
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!");
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        int linhaSelecionada = tabela.getSelectedRow();
    
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um animal na tabela primeiro!");
            return;
        }

        idJTextField.setText(tabela.getValueAt(linhaSelecionada, 0).toString());
        nomeJTextField.setText(tabela.getValueAt(linhaSelecionada, 1).toString());
        especieJTextField.setText(tabela.getValueAt(linhaSelecionada, 2).toString());
        racaJTextField.setText(tabela.getValueAt(linhaSelecionada, 3).toString());
        idadeJTextField.setText(tabela.getValueAt(linhaSelecionada, 4).toString());
        statusJTextField.setText(tabela.getValueAt(linhaSelecionada, 5).toString());
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void racaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_racaJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JButton editarJButton;
    private javax.swing.JLabel especieJLabel;
    private javax.swing.JTextField especieJTextField;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JLabel idadeJLabel;
    private javax.swing.JTextField idadeJTextField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JLabel racaJLabel;
    private javax.swing.JTextField racaJTextField;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JTextField statusJTextField;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
