/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaabrigoanimais.ui;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistemaabrigoanimais.Animal;
import com.mycompany.sistemaabrigoanimais.persistencia.IAnimalDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.AnimalDAOImplPostgres;
/**
 *
 * @author Giovana
 */
public class AnimalJPanel extends javax.swing.JPanel {
    
    private IAnimalDAO animalDAO = new AnimalDAOImplPostgres();
    /**
     * Creates new form AnimalJPanel
     */
    public AnimalJPanel() {
        initComponents();
        carregarTabela();
    }
    
    private void carregarTabela() {
        DefaultTableModel dfm = (DefaultTableModel) tabela.getModel();
        dfm.setRowCount(0);
        String termoBusca = buscaJTextField.getText().toLowerCase();
        String criterio = filtroJComboBox.getSelectedItem().toString();

        List<Animal> lista = animalDAO.consultar();

        for (Animal animal : lista) {
            String valorComparar = "";

            switch (criterio) {
                case "Nome": valorComparar = animal.getNome(); break;
                case "Espécie": valorComparar = animal.getEspecie(); break;
                case "Raça": valorComparar = animal.getRaca(); break;
                case "Status": valorComparar = animal.getStatus(); break;
            }

            if (termoBusca.isEmpty() || valorComparar.toLowerCase().contains(termoBusca)) {
                Object[] linha = new Object[6];
                linha[0] = animal.getId();
                linha[1] = animal.getNome();
                linha[2] = animal.getEspecie();
                linha[3] = animal.getRaca();
                linha[4] = animal.getIdade();
                linha[5] = animal.getStatus();
                dfm.addRow(linha);
            }
        }
    }
    
    private void limparCampos() {
        idJTextField.setText("");
        nomeJTextField.setText("");
        especieJTextField.setText("");
        racaJTextField.setText("");
        idadeJTextField.setText("");
        statusJTextField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        nomeJLabel = new javax.swing.JLabel();
        nomeJTextField = new javax.swing.JTextField();
        especieJLabel = new javax.swing.JLabel();
        especieJTextField = new javax.swing.JTextField();
        salvarJButton = new javax.swing.JButton();
        racaJLabel = new javax.swing.JLabel();
        racaJTextField = new javax.swing.JTextField();
        idadeJLabel = new javax.swing.JLabel();
        idadeJTextField = new javax.swing.JTextField();
        statusJLabel = new javax.swing.JLabel();
        statusJTextField = new javax.swing.JTextField();
        cancelarJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        scrollTabela = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        editarJButton = new javax.swing.JButton();
        idJLabel = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        buscaJTextField = new javax.swing.JTextField();
        buscaJLabel = new javax.swing.JLabel();
        filtroJComboBox = new javax.swing.JComboBox<>();
        voltarJButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        nomeJLabel.setText("Nome:");

        especieJLabel.setText("Espécie:");

        especieJTextField.addActionListener(this::especieJTextFieldActionPerformed);

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        racaJLabel.setText("Raça:");

        racaJTextField.addActionListener(this::racaJTextFieldActionPerformed);

        idadeJLabel.setText("Idade:");

        statusJLabel.setText("Status:");

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(this::cancelarJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "nome", "especie", "raça", "idade", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTabela.setViewportView(tabela);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        idJLabel.setText("Id: ");

        idJTextField.setEditable(false);

        buscaJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscaJTextFieldKeyReleased(evt);
            }
        });

        buscaJLabel.setText("Buscar:");

        filtroJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Espécie", "Raça", "Status" }));
        filtroJComboBox.addActionListener(this::filtroJComboBoxActionPerformed);

        voltarJButton1.setText("Voltar");
        voltarJButton1.addActionListener(this::voltarJButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(excluirJButton)
                            .addComponent(editarJButton)
                            .addComponent(voltarJButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeJLabel)
                            .addComponent(racaJLabel)
                            .addComponent(buscaJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filtroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(racaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(idadeJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(statusJLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(statusJTextField))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addComponent(salvarJButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(cancelarJButton)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nomeJTextField)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(especieJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(especieJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(idJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJLabel)
                    .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especieJLabel)
                    .addComponent(especieJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idJLabel)
                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(racaJLabel)
                    .addComponent(racaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idadeJLabel)
                    .addComponent(idadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusJLabel)
                    .addComponent(statusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarJButton)
                    .addComponent(salvarJButton))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaJLabel)
                    .addComponent(filtroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excluirJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarJButton1)
                        .addGap(19, 19, 19))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        String idStr = idJTextField.getText();
        
        if (idStr.equals("")) {
            JOptionPane.showMessageDialog(this, "Para novos cadastros, utilize a tela de Registar Resgate.");
            return;
        }

        try {
            Animal animal = new Animal();
            animal.setId(Integer.parseInt(idStr));
            animal.setNome(nomeJTextField.getText());
            animal.setEspecie(especieJTextField.getText());
            animal.setRaca(racaJTextField.getText());
            animal.setIdade(Integer.parseInt(idadeJTextField.getText())); 
            animal.setStatus(statusJTextField.getText());

            animalDAO.atualizar(animal);

            JOptionPane.showMessageDialog(this, "Dados do animal atualizados com sucesso!");
            limparCampos();
            carregarTabela(); 
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + erro.getMessage());
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void especieJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieJTextFieldActionPerformed

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        limparCampos();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int id = (int) tabela.getValueAt(linhaSelecionada, 0);

            Animal a = new Animal();
            a.setId(id);

            int confirma = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?");
            if (confirma == JOptionPane.YES_OPTION) {
                animalDAO.remover(a);
                carregarTabela();
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!");
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        int linhaSelecionada = tabela.getSelectedRow();
    
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um animal na tabela primeiro!");
            return;
        }

        idJTextField.setText(tabela.getValueAt(linhaSelecionada, 0).toString());
        nomeJTextField.setText(tabela.getValueAt(linhaSelecionada, 1).toString());
        especieJTextField.setText(tabela.getValueAt(linhaSelecionada, 2).toString());
        racaJTextField.setText(tabela.getValueAt(linhaSelecionada, 3).toString());
        idadeJTextField.setText(tabela.getValueAt(linhaSelecionada, 4).toString());
        statusJTextField.setText(tabela.getValueAt(linhaSelecionada, 5).toString());
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void racaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_racaJTextFieldActionPerformed

    private void buscaJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaJTextFieldKeyReleased
        carregarTabela();
    }//GEN-LAST:event_buscaJTextFieldKeyReleased

    private void filtroJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroJComboBoxActionPerformed
        carregarTabela();
    }//GEN-LAST:event_filtroJComboBoxActionPerformed

    private void voltarJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarJButton1ActionPerformed
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (win instanceof TelaJFrame) {
            TelaJFrame telaPrincipal = (TelaJFrame) win;
            telaPrincipal.limparPainelPrincipal();
        }
    }//GEN-LAST:event_voltarJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscaJLabel;
    private javax.swing.JTextField buscaJTextField;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JButton editarJButton;
    private javax.swing.JLabel especieJLabel;
    private javax.swing.JTextField especieJTextField;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JComboBox<String> filtroJComboBox;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JLabel idadeJLabel;
    private javax.swing.JTextField idadeJTextField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JLabel racaJLabel;
    private javax.swing.JTextField racaJTextField;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JTextField statusJTextField;
    private javax.swing.JTable tabela;
    private javax.swing.JButton voltarJButton1;
    // End of variables declaration//GEN-END:variables
}
