/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaabrigoanimais.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistemaabrigoanimais.Consulta;
import com.mycompany.sistemaabrigoanimais.Animal;
import com.mycompany.sistemaabrigoanimais.Veterinario;
import com.mycompany.sistemaabrigoanimais.Secretaria;
import com.mycompany.sistemaabrigoanimais.persistencia.IConsultaDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.ConsultaDAOImplPostgres;
import com.mycompany.sistemaabrigoanimais.persistencia.IAnimalDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.AnimalDAOImplPostgres;
import com.mycompany.sistemaabrigoanimais.persistencia.IVeterinarioDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.VeterinarioDAOImplPostgres;
import com.mycompany.sistemaabrigoanimais.persistencia.ISecretariaDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.SecretariaDAOImplPostgres;
/**
 *
 * @author Giovana
 */
public class ConsultaJPanel extends javax.swing.JPanel {
    private IConsultaDAO consultaDAO = new ConsultaDAOImplPostgres();
    private IAnimalDAO animalDAO = new AnimalDAOImplPostgres();
    private IVeterinarioDAO vetDAO = new VeterinarioDAOImplPostgres();
    private ISecretariaDAO secDAO = new SecretariaDAOImplPostgres();
    
    private int idSelecionado = -1;
    
    /**
     * Creates new form ConsultaJPanel
     */
    public ConsultaJPanel() {
        initComponents();
        carregarSeletores(); 
        carregarTabela();
    }
    
    private void carregarSeletores() {
        animalJComboBox.removeAllItems();
        for (Animal a : animalDAO.consultar()) {
            animalJComboBox.addItem(a.getNome()); // Adicionamos o nome para exibição
        }

        veterinarioJComboBox.removeAllItems();
        for (Veterinario v : vetDAO.consultar()) {
            veterinarioJComboBox.addItem(v.getNome());
        }

        secretariaJComboBox.removeAllItems();
        for (Secretaria s : secDAO.consultar()) {
            secretariaJComboBox.addItem(s.getNome());
        }
    }
    
    private void carregarTabela() {
        DefaultTableModel dfm = (DefaultTableModel) tabela.getModel();
        dfm.setRowCount(0);

        // Pegamos o termo de busca e o filtro selecionado
        String termo = buscarJTextField.getText().toLowerCase();
        String filtro = filtroJComboBox.getSelectedItem().toString();

        List<Consulta> lista = consultaDAO.consultar();
        for (Consulta c : lista) {
            // Buscamos os nomes para comparação e exibição
            String nomeAnimal = "Desconhecido";
            for(Animal a : animalDAO.consultar()) {
                if(a.getId() == c.getAnimal().getId()) { nomeAnimal = a.getNome(); break; }
            }

            String nomeVet = "Desconhecido";
            for(Veterinario v : vetDAO.consultar()) {
                if(v.getId() == c.getVeterinario().getId()) { nomeVet = v.getNome(); break; }
            }

            String nomeSec = "Desconhecida";
            for(Secretaria s : secDAO.consultar()) {
                if(s.getId() == c.getSecretaria().getId()) { nomeSec = s.getNome(); break; }
            }

            // Lógica de Filtro
            String valorComparar = "";
            if (filtro.equals("Data Consulta")) valorComparar = c.getDataConsulta();
            else if (filtro.equals("Animal")) valorComparar = nomeAnimal;
            else if (filtro.equals("Veterinario")) valorComparar = nomeVet;
            else if (filtro.equals("Secretaria")) valorComparar = nomeSec;

            // Só adiciona na tabela se bater com a busca ou se a busca estiver vazia
            if (termo.isEmpty() || valorComparar.toLowerCase().contains(termo)) {
                Object[] linha = { c.getId(), c.getDataConsulta(), nomeAnimal, nomeVet, nomeSec };
                dfm.addRow(linha);
            }
        }
    }
    
    private void limparCampos() {
        dataConsultaJTextField.setText("");
        idSelecionado = -1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataConsultaJLabel = new javax.swing.JLabel();
        animalJLabel = new javax.swing.JLabel();
        veterinarioJLabel = new javax.swing.JLabel();
        secretariaJLabel = new javax.swing.JLabel();
        dataConsultaJTextField = new javax.swing.JTextField();
        animalJComboBox = new javax.swing.JComboBox<>();
        veterinarioJComboBox = new javax.swing.JComboBox<>();
        cancelarJButton = new javax.swing.JButton();
        salvarJButton = new javax.swing.JButton();
        buscarJLabel = new javax.swing.JLabel();
        buscarJTextField = new javax.swing.JTextField();
        filtroJComboBox = new javax.swing.JComboBox<>();
        tabelaScroll = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        editarJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        voltarJButton = new javax.swing.JButton();
        secretariaJComboBox = new javax.swing.JComboBox<>();

        dataConsultaJLabel.setText("Data Consulta:");

        animalJLabel.setText("Animal:");

        veterinarioJLabel.setText("Veterinário:");

        secretariaJLabel.setText("Secretária:");

        animalJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        veterinarioJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(this::cancelarJButtonActionPerformed);

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        buscarJLabel.setText("Buscar:");

        buscarJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarJTextFieldKeyReleased(evt);
            }
        });

        filtroJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Consulta", "Animal", "Veterinario", "Secretaria" }));
        filtroJComboBox.addActionListener(this::filtroJComboBoxActionPerformed);
        filtroJComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroJComboBoxKeyReleased(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Data Consulta", "Animal", "Veterinário", "Secretária"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaScroll.setViewportView(tabela);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        voltarJButton.setText("Voltar");
        voltarJButton.addActionListener(this::voltarJButtonActionPerformed);

        secretariaJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataConsultaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataConsultaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(animalJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(animalJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veterinarioJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veterinarioJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(secretariaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secretariaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(tabelaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarJButton)
                            .addComponent(excluirJButton)
                            .addComponent(voltarJButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarJButton)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataConsultaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animalJLabel)
                    .addComponent(animalJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veterinarioJLabel)
                    .addComponent(dataConsultaJLabel)
                    .addComponent(veterinarioJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secretariaJLabel)
                    .addComponent(secretariaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarJButton)
                    .addComponent(cancelarJButton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarJLabel)
                    .addComponent(buscarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarJButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        limparCampos();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        try {
            Consulta c = new Consulta();
            c.setDataConsulta(dataConsultaJTextField.getText());

            // Buscamos os objetos completos pelos índices selecionados
            c.setAnimal(animalDAO.consultar().get(animalJComboBox.getSelectedIndex()));
            c.setVeterinario(vetDAO.consultar().get(veterinarioJComboBox.getSelectedIndex()));
            c.setSecretaria(secDAO.consultar().get(secretariaJComboBox.getSelectedIndex()));

            if (idSelecionado == -1) {
                consultaDAO.inserir(c);
                JOptionPane.showMessageDialog(this, "Consulta agendada!");
            } else {
                c.setId(idSelecionado);
                consultaDAO.atualizar(c);
                JOptionPane.showMessageDialog(this, "Consulta atualizada!");
            }
            carregarTabela();
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma consulta na tabela!");
            return;
        }

        int id = (int) tabela.getValueAt(linha, 0);

        for (Consulta c : consultaDAO.consultar()) {
            if (c.getId() == id) {
                idSelecionado = c.getId();
                dataConsultaJTextField.setText(c.getDataConsulta());

                animalJComboBox.setSelectedItem(buscarNomeAnimal(c.getAnimal().getId()));
                veterinarioJComboBox.setSelectedItem(buscarNomeVet(c.getVeterinario().getId()));
                secretariaJComboBox.setSelectedItem(buscarNomeSec(c.getSecretaria().getId()));
                break;
            }
        }
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void voltarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarJButtonActionPerformed
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof TelaJFrame) {
            ((TelaJFrame) win).limparPainelPrincipal();
        }
    }//GEN-LAST:event_voltarJButtonActionPerformed

    private void buscarJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarJTextFieldKeyReleased
        carregarTabela();
    }//GEN-LAST:event_buscarJTextFieldKeyReleased

    private void filtroJComboBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroJComboBoxKeyReleased
        
    }//GEN-LAST:event_filtroJComboBoxKeyReleased

    private void filtroJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroJComboBoxActionPerformed
        carregarTabela();
    }//GEN-LAST:event_filtroJComboBoxActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma consulta para excluir!");
            return;
        }

        int confirma = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este agendamento?");
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                int id = (int) tabela.getValueAt(linha, 0);
                Consulta c = new Consulta();
                c.setId(id);

                consultaDAO.remover(c); //

                JOptionPane.showMessageDialog(this, "Consulta excluída!");
                carregarTabela();
                limparCampos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed
    private String buscarNomeAnimal(int id) {
        for(Animal a : animalDAO.consultar()) if(a.getId() == id) return a.getNome();
        return "";
    }
    private String buscarNomeVet(int id) {
        for(Veterinario v : vetDAO.consultar()) if(v.getId() == id) return v.getNome();
        return "";
    }
    private String buscarNomeSec(int id) {
        for(Secretaria s : secDAO.consultar()) if(s.getId() == id) return s.getNome();
        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> animalJComboBox;
    private javax.swing.JLabel animalJLabel;
    private javax.swing.JLabel buscarJLabel;
    private javax.swing.JTextField buscarJTextField;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JLabel dataConsultaJLabel;
    private javax.swing.JTextField dataConsultaJTextField;
    private javax.swing.JButton editarJButton;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JComboBox<String> filtroJComboBox;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JComboBox<String> secretariaJComboBox;
    private javax.swing.JLabel secretariaJLabel;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelaScroll;
    private javax.swing.JComboBox<String> veterinarioJComboBox;
    private javax.swing.JLabel veterinarioJLabel;
    private javax.swing.JButton voltarJButton;
    // End of variables declaration//GEN-END:variables
}
