/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaabrigoanimais.ui;

/**
 *
 * @author Giovana
 */
public class DashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardJPanel
     */
    public DashboardJPanel() {
        initComponents();
    }
    
    private void trocarTela(javax.swing.JPanel novaTela) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof TelaJFrame) {
            ((TelaJFrame) win).exibirPainel(novaTela);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resgateJButton = new javax.swing.JButton();
        consultaJButton = new javax.swing.JButton();
        adocaoJButton = new javax.swing.JButton();
        veterinarioJButton = new javax.swing.JButton();
        secretariaJButton = new javax.swing.JButton();
        animalJButton = new javax.swing.JButton();
        conteudoJPanel = new javax.swing.JPanel();
        sairJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        resgateJButton.setText("RESGATE");
        resgateJButton.addActionListener(this::resgateJButtonActionPerformed);

        consultaJButton.setText("CONSULTA");
        consultaJButton.addActionListener(this::consultaJButtonActionPerformed);

        adocaoJButton.setText("ADOÇÃO");
        adocaoJButton.addActionListener(this::adocaoJButtonActionPerformed);

        veterinarioJButton.setText("VETERINÁRIO");
        veterinarioJButton.addActionListener(this::veterinarioJButtonActionPerformed);

        secretariaJButton.setText("SECRETÁRIA");
        secretariaJButton.addActionListener(this::secretariaJButtonActionPerformed);

        animalJButton.setText("ANIMAL");
        animalJButton.addActionListener(this::animalJButtonActionPerformed);

        sairJButton.setText("Sair");
        sairJButton.addActionListener(this::sairJButtonActionPerformed);

        jLabel1.setText("                                         SISTEMA DE GESTÃO PARA ABRIGO DE ANIMAIS");

        javax.swing.GroupLayout conteudoJPanelLayout = new javax.swing.GroupLayout(conteudoJPanel);
        conteudoJPanel.setLayout(conteudoJPanelLayout);
        conteudoJPanelLayout.setHorizontalGroup(
            conteudoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteudoJPanelLayout.createSequentialGroup()
                .addGroup(conteudoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conteudoJPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sairJButton))
                    .addGroup(conteudoJPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)))
                .addContainerGap())
        );
        conteudoJPanelLayout.setVerticalGroup(
            conteudoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteudoJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(sairJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conteudoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(animalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resgateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secretariaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adocaoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(veterinarioJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(conteudoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adocaoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resgateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(consultaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(animalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secretariaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veterinarioJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sairJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairJButtonActionPerformed
        int confirma = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Deseja realmente fechar o sistema?", "Sair", 
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirma == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_sairJButtonActionPerformed

    private void adocaoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adocaoJButtonActionPerformed
        trocarTela(new AdocaoJPanel());
    }//GEN-LAST:event_adocaoJButtonActionPerformed

    private void veterinarioJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veterinarioJButtonActionPerformed
        trocarTela(new VeterinarioJPanel());
    }//GEN-LAST:event_veterinarioJButtonActionPerformed

    private void secretariaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretariaJButtonActionPerformed
        trocarTela(new SecretariaJPanel());
    }//GEN-LAST:event_secretariaJButtonActionPerformed

    private void consultaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaJButtonActionPerformed
        trocarTela(new ConsultaJPanel());
    }//GEN-LAST:event_consultaJButtonActionPerformed

    private void resgateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resgateJButtonActionPerformed
        trocarTela(new ResgateJPanel());
    }//GEN-LAST:event_resgateJButtonActionPerformed

    private void animalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalJButtonActionPerformed
        trocarTela(new AnimalJPanel());
    }//GEN-LAST:event_animalJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adocaoJButton;
    private javax.swing.JButton animalJButton;
    private javax.swing.JButton consultaJButton;
    private javax.swing.JPanel conteudoJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resgateJButton;
    private javax.swing.JButton sairJButton;
    private javax.swing.JButton secretariaJButton;
    private javax.swing.JButton veterinarioJButton;
    // End of variables declaration//GEN-END:variables
}
