/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaabrigoanimais.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistemaabrigoanimais.Secretaria;
import com.mycompany.sistemaabrigoanimais.persistencia.ISecretariaDAO;
import com.mycompany.sistemaabrigoanimais.persistencia.SecretariaDAOImplPostgres;
/**
 *
 * @author Giovana
 */
public class SecretariaJPanel extends javax.swing.JPanel {
    private ISecretariaDAO secDAO = new SecretariaDAOImplPostgres();
    private int idSelecionado = -1;
    /**
     * Creates new form SecretariaJPanel
     */
    public SecretariaJPanel() {
        initComponents();
        carregarTabela();
    }
    
    private void carregarTabela() {
        DefaultTableModel dfm = (DefaultTableModel) tabela.getModel();
        dfm.setRowCount(0);
        String termo = buscarJTextField.getText().toLowerCase();
        String filtro = filtroJComboBox.getSelectedItem().toString();

        List<Secretaria> lista = secDAO.consultar();
        for (Secretaria s : lista) {
            String valorComparar = "";
            if (filtro.equals("Nome")) valorComparar = s.getNome();
            else if (filtro.equals("CPF")) valorComparar = s.getCpf();
            else if (filtro.equals("E-mail")) valorComparar = s.getEmail();

            if (termo.isEmpty() || valorComparar.toLowerCase().contains(termo)) {
                Object[] linha = { 
                    s.getId(),              
                    s.getNome(),             
                    s.getCpf(),             
                    s.getTelefone(),         
                    s.getDataNascimento(),   
                    s.getSalario(),          
                    s.getEmail()             
                };
                dfm.addRow(linha);
            }
        }
    }
    
    private void limparCampos() {
        nomeJTextField.setText("");
        cpfJTextField.setText("");
        telefoneJTextField.setText("");
        emailJTextField.setText("");
        dataNascimentoJTextField.setText("");
        salarioJTextField.setText("");
        buscarJTextField.setText("");
        idSelecionado = -1; // Reseta para indicar novo cadastro
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeJLabel = new javax.swing.JLabel();
        cpfJLabel = new javax.swing.JLabel();
        telefoneJLabel = new javax.swing.JLabel();
        dataNascimentoJLabel = new javax.swing.JLabel();
        salarioJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        nomeJTextField = new javax.swing.JTextField();
        telefoneJTextField = new javax.swing.JTextField();
        cpfJTextField = new javax.swing.JTextField();
        dataNascimentoJTextField = new javax.swing.JTextField();
        salarioJTextField = new javax.swing.JTextField();
        emailJTextField = new javax.swing.JTextField();
        tabelaScroll = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        cancelarJButton = new javax.swing.JButton();
        salvarJButton = new javax.swing.JButton();
        editarJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        filtroJComboBox = new javax.swing.JComboBox<>();
        buscarJLabel = new javax.swing.JLabel();
        buscarJTextField = new javax.swing.JTextField();
        voltarJButton = new javax.swing.JButton();

        nomeJLabel.setText("Nome:");

        cpfJLabel.setText("CPF:");

        telefoneJLabel.setText("Telefone:");

        dataNascimentoJLabel.setText("Data Nascimento:");

        salarioJLabel.setText("Salário:");

        emailJLabel.setText("E-mail:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "CPF", "Telefone", "Data Nascimento", "Salário", "E-mail"
            }
        ));
        tabelaScroll.setViewportView(tabela);

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(this::cancelarJButtonActionPerformed);

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        filtroJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF", "E-mail" }));
        filtroJComboBox.addActionListener(this::filtroJComboBoxActionPerformed);

        buscarJLabel.setText("Buscar:");

        buscarJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarJTextFieldKeyReleased(evt);
            }
        });

        voltarJButton.setText("Voltar");
        voltarJButton.addActionListener(this::voltarJButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salvarJButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(buscarJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(filtroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tabelaScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarJButton)
                            .addComponent(editarJButton)
                            .addComponent(excluirJButton)
                            .addComponent(voltarJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpfJLabel)
                            .addComponent(nomeJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpfJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataNascimentoJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataNascimentoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneJTextField))
                            .addComponent(buscarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJLabel)
                    .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailJLabel)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfJLabel)
                    .addComponent(cpfJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascimentoJLabel)
                    .addComponent(dataNascimentoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioJLabel)
                    .addComponent(salarioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneJLabel)
                    .addComponent(telefoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarJButton)
                    .addComponent(salvarJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarJLabel)
                    .addComponent(buscarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabelaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarJButton)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        try {
            Secretaria s = new Secretaria();
            s.setNome(nomeJTextField.getText());
            s.setCpf(cpfJTextField.getText());
            s.setTelefone(telefoneJTextField.getText());
            s.setEmail(emailJTextField.getText());
            s.setDataNascimento(dataNascimentoJTextField.getText());

            String salarioTexto = salarioJTextField.getText().replace(",", ".");
            s.setSalario(Float.parseFloat(salarioTexto));

            if (idSelecionado == -1) {
                secDAO.inserir(s);
                JOptionPane.showMessageDialog(this, "Secretária cadastrada!");
            } else {
                s.setId(idSelecionado);
                secDAO.atualizar(s);
                JOptionPane.showMessageDialog(this, "Dados atualizados!");
            }
            carregarTabela();
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha == -1) return;

        List<Secretaria> lista = secDAO.consultar();
        Secretaria s = lista.get(linha);

        idSelecionado = s.getId();
        nomeJTextField.setText(s.getNome());
        cpfJTextField.setText(s.getCpf());
        telefoneJTextField.setText(s.getTelefone());
        emailJTextField.setText(s.getEmail());
        dataNascimentoJTextField.setText(s.getDataNascimento());
        salarioJTextField.setText(String.valueOf(s.getSalario()));
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma secretária para excluir.");
            return;
        }

        int confirma = JOptionPane.showConfirmDialog(this, "Confirma a exclusão?");
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                int id = (int) tabela.getValueAt(linha, 0); // Pega o ID da primeira coluna
                Secretaria s = new Secretaria();
                s.setId(id);
                secDAO.remover(s);

                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
                carregarTabela();
                limparCampos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        limparCampos();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void voltarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarJButtonActionPerformed
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof TelaJFrame) {
            ((TelaJFrame) win).limparPainelPrincipal(); // Usa o método universal da JFrame
        }
    }//GEN-LAST:event_voltarJButtonActionPerformed

    private void buscarJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarJTextFieldKeyReleased
        carregarTabela();
    }//GEN-LAST:event_buscarJTextFieldKeyReleased

    private void filtroJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroJComboBoxActionPerformed
        carregarTabela();
    }//GEN-LAST:event_filtroJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarJLabel;
    private javax.swing.JTextField buscarJTextField;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JTextField cpfJTextField;
    private javax.swing.JLabel dataNascimentoJLabel;
    private javax.swing.JTextField dataNascimentoJTextField;
    private javax.swing.JButton editarJButton;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JComboBox<String> filtroJComboBox;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JLabel salarioJLabel;
    private javax.swing.JTextField salarioJTextField;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelaScroll;
    private javax.swing.JLabel telefoneJLabel;
    private javax.swing.JTextField telefoneJTextField;
    private javax.swing.JButton voltarJButton;
    // End of variables declaration//GEN-END:variables
}
