/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaabrigoanimais.ui;

/**
 *
 * @author Giovana
 */
public class TelaJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaJFrame.class.getName());

    /**
     * Creates new form TelaJFrame
     */
    public TelaJFrame() {
        initComponents();
        this.setSize(900, 700);
        this.setLocationRelativeTo(null);
    }
    
    public void limparPainelPrincipal() {
        conteudoJPanel.removeAll();
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteudoJPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastrosJMenu = new javax.swing.JMenu();
        animalJMenuItem = new javax.swing.JMenuItem();
        resgateJMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conteudoJPanel.setLayout(new javax.swing.BoxLayout(conteudoJPanel, javax.swing.BoxLayout.LINE_AXIS));

        cadastrosJMenu.setText("Cadastros");

        animalJMenuItem.setText("Animal");
        animalJMenuItem.addActionListener(this::animalJMenuItemActionPerformed);
        cadastrosJMenu.add(animalJMenuItem);

        resgateJMenuItem.setText("Resgate");
        resgateJMenuItem.addActionListener(this::resgateJMenuItemActionPerformed);
        cadastrosJMenu.add(resgateJMenuItem);

        jMenuBar1.add(cadastrosJMenu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animalJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalJMenuItemActionPerformed
        AnimalJPanel tela = new AnimalJPanel();

        conteudoJPanel.removeAll();
        conteudoJPanel.add(tela);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }//GEN-LAST:event_animalJMenuItemActionPerformed

    private void resgateJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resgateJMenuItemActionPerformed
        ResgateJPanel tela = new ResgateJPanel();
    
        conteudoJPanel.removeAll();
        conteudoJPanel.add(tela);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }//GEN-LAST:event_resgateJMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem animalJMenuItem;
    private javax.swing.JMenu cadastrosJMenu;
    private javax.swing.JPanel conteudoJPanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem resgateJMenuItem;
    // End of variables declaration//GEN-END:variables
}
