/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaabrigoanimais.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistemaabrigoanimais.Veterinario; 
import com.mycompany.sistemaabrigoanimais.persistencia.IVeterinarioDAO; 
import com.mycompany.sistemaabrigoanimais.persistencia.VeterinarioDAOImplPostgres; 
/**
 *
 * @author Giovana
 */
public class VeterinarioJPanel extends javax.swing.JPanel {
    private IVeterinarioDAO vetDAO = new VeterinarioDAOImplPostgres();
    private int idSelecionado = -1;
    /**
     * Creates new form VeterinarioJPanel
     */
    public VeterinarioJPanel() {
        initComponents();
        carregarTabela();
    }
    private void limparCampos() {
        nomeJTextField.setText("");
        cpfJTextField.setText("");
        crmvJTextField.setText("");
        especialidadeJTextField.setText("");
        salarioJTextField.setText("");
        buscarJTextField.setText("");
        idSelecionado = -1;
    }
    private void carregarTabela() {
        DefaultTableModel dfm = (DefaultTableModel) tabela.getModel();
        dfm.setRowCount(0);

        String termo = buscarJTextField.getText().toLowerCase();
        String filtro = filtroJComboBox.getSelectedItem().toString();

        List<Veterinario> lista = vetDAO.consultar();
        for (Veterinario v : lista) {
            String valorComparar = "";
            if (filtro.equals("Nome")) valorComparar = v.getNome();
            else if (filtro.equals("CPF")) valorComparar = v.getCpf();
            else if (filtro.equals("CRMV")) valorComparar = v.getCrmv();
            else if (filtro.equals("Especialidade")) valorComparar = v.getEspecialidade();

            if (termo.isEmpty() || valorComparar.toLowerCase().contains(termo)) {
                Object[] linha = { v.getId(), v.getNome(), v.getCpf(), v.getCrmv(), v.getEspecialidade() };
                dfm.addRow(linha);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeJLabel = new javax.swing.JLabel();
        cpfJLabel = new javax.swing.JLabel();
        crmvJLabel = new javax.swing.JLabel();
        especialidadeJLabel = new javax.swing.JLabel();
        salarioJLabel = new javax.swing.JLabel();
        nomeJTextField = new javax.swing.JTextField();
        crmvJTextField = new javax.swing.JTextField();
        salarioJTextField = new javax.swing.JTextField();
        cpfJTextField = new javax.swing.JTextField();
        especialidadeJTextField = new javax.swing.JTextField();
        cancelarJButton = new javax.swing.JButton();
        salvarJButton = new javax.swing.JButton();
        editarJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        voltarJButton = new javax.swing.JButton();
        tabelaScroll = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        filtroJComboBox = new javax.swing.JComboBox<>();
        buscarJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buscarJLabel = new javax.swing.JLabel();

        nomeJLabel.setText("Nome:");

        cpfJLabel.setText("CPF:");

        crmvJLabel.setText("CRMV:");

        especialidadeJLabel.setText("Especialidade:");

        salarioJLabel.setText("Sálario:");

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(this::cancelarJButtonActionPerformed);

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        voltarJButton.setText("Voltar");
        voltarJButton.addActionListener(this::voltarJButtonActionPerformed);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "CPF", "CRMV", "Especialidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaScroll.setViewportView(tabela);

        filtroJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF", "CRMV", "Especialidade" }));

        buscarJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarJTextFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("jLabel1");

        buscarJLabel.setText("Buscar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeJLabel)
                            .addComponent(cpfJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crmvJLabel))
                            .addComponent(cpfJTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crmvJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(especialidadeJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(especialidadeJTextField))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tabelaScroll)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(salvarJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(buscarJLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filtroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarJButton)
                            .addComponent(editarJButton)
                            .addComponent(excluirJButton)
                            .addComponent(voltarJButton))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJLabel)
                    .addComponent(crmvJLabel)
                    .addComponent(salarioJLabel)
                    .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crmvJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfJLabel)
                    .addComponent(cpfJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especialidadeJLabel)
                    .addComponent(especialidadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarJButton)
                    .addComponent(cancelarJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(editarJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(excluirJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(voltarJButton))
                            .addComponent(tabelaScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        limparCampos();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void voltarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarJButtonActionPerformed
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof TelaJFrame) {
            ((TelaJFrame) win).limparPainelPrincipal();
        }
    }//GEN-LAST:event_voltarJButtonActionPerformed

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        try {
            Veterinario v = new Veterinario();
            v.setNome(nomeJTextField.getText());
            v.setCpf(cpfJTextField.getText());
            v.setCrmv(crmvJTextField.getText());
            v.setEspecialidade(especialidadeJTextField.getText());

            String salarioTexto = salarioJTextField.getText().replace(",", ".");
            v.setSalario(Float.parseFloat(salarioTexto));

            if (idSelecionado == -1) { 
                vetDAO.inserir(v);
                JOptionPane.showMessageDialog(this, "Veterinário cadastrado!");
            } else {
                v.setId(idSelecionado);
                vetDAO.atualizar(v);
                JOptionPane.showMessageDialog(this, "Dados atualizados!");
            }

            carregarTabela();
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void buscarJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarJTextFieldKeyReleased
        carregarTabela();
    }//GEN-LAST:event_buscarJTextFieldKeyReleased

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        int linhaSelecionada = tabela.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um veterinário na tabela primeiro!");
            return;
        }

        List<Veterinario> lista = vetDAO.consultar();
        Veterinario v = lista.get(linhaSelecionada);
        idSelecionado = v.getId();

        nomeJTextField.setText(v.getNome());
        cpfJTextField.setText(v.getCpf());
        crmvJTextField.setText(v.getCrmv());
        especialidadeJTextField.setText(v.getEspecialidade());
        salarioJTextField.setText(String.valueOf(v.getSalario()));
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int linhaSelecionada = tabela.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione quem deseja excluir.");
            return;
        }

        int confirma = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este veterinário?");

        if (confirma == JOptionPane.YES_OPTION) {
            try {
                int id = (int) tabela.getValueAt(linhaSelecionada, 0);

                Veterinario v = new Veterinario();
                v.setId(id);
                vetDAO.remover(v);
                JOptionPane.showMessageDialog(this, "Veterinário excluído com sucesso!");
                carregarTabela();
                limparCampos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarJLabel;
    private javax.swing.JTextField buscarJTextField;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JTextField cpfJTextField;
    private javax.swing.JLabel crmvJLabel;
    private javax.swing.JTextField crmvJTextField;
    private javax.swing.JButton editarJButton;
    private javax.swing.JLabel especialidadeJLabel;
    private javax.swing.JTextField especialidadeJTextField;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JComboBox<String> filtroJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JLabel salarioJLabel;
    private javax.swing.JTextField salarioJTextField;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelaScroll;
    private javax.swing.JButton voltarJButton;
    // End of variables declaration//GEN-END:variables
}
